# Generated by Django 4.2.6 on 2023-11-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "UsersApp",
            "0002_role_remove_superiority_grade_alter_superiority_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UsersApp.role",
            ),
        ),
    ]
