# Generated by Django 4.2.6 on 2023-11-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0003_alter_profile_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="role",
            new_name="superiority",
        ),
    ]
