# Generated by Django 4.2.6 on 2023-11-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0004_rename_role_profile_superiority"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Superiority",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="superiority",
            new_name="role",
        ),
    ]
