# Generated by Django 4.2.6 on 2023-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0005_delete_superiority_rename_superiority_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
