# Generated by Django 4.2.6 on 2023-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0009_assignroomtask_room_delete_assigntask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
