# Generated by Django 4.2.6 on 2023-11-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0010_room_floor"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("free", "free"),
                    ("occupied", "occupied"),
                    ("cleaning", "cleaning"),
                    ("readyToClean", "readyToClean"),
                ],
                default="free",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UsersApp.roomtype",
            ),
        ),
    ]
