# Generated by Django 4.2.7 on 2023-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0011_roomtype_room_number_room_status_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignroomtask",
            name="descriere",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
