# Generated by Django 4.2.7 on 2023-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0012_alter_assignroomtask_descriere_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignroomtask',
            name='task',
        ),
        migrations.AddField(
            model_name='assignroomtask',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='UsersApp.task'),
        ),
    ]
