# Generated by Django 4.2.6 on 2024-01-14 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("UsersApp", "0013_remove_assignroomtask_task_assignroomtask_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignroomtask",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
