# Generated by Django 4.2.6 on 2024-01-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0014_alter_assignroomtask_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="image",
            new_name="profile_image",
        ),
    ]
