# Generated by Django 4.2.6 on 2024-02-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0014_alter_assignroomtask_room"),
        ("UsersApp", "0015_rename_image_profile_profile_image"),
    ]

    operations = []
