# Generated by Django 4.2.6 on 2024-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0016_merge_20240201_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.PositiveSmallIntegerField(default=1, max_length=100),
        ),
    ]
